### ISSUE TITLE
As a user I want to be able to add a bio, so labour today can learn more about me.

### ISSUE THREAD

**Issue by johnreid01** [labour-today/backend#13]
Completion:
This allows the user to feel more entitled and cared for.
When you as a worker log into your profile you'll be able to see your bio and edit it

Test:
Create a test profile.
Enter skills etc
Create bio.
Review and save.
View profile.

**Comment by thatdanghill** [comment]
Time: 2hr

TODO:
Add in Bio field to models
Update profile view with bio form
