### ISSUE TITLE
As an admin i want to be able to search our back end data base so that i can quickly and easily find certain names or certain skills 

### ISSUE THREAD

**Issue by seb-jacob** [labour-today/backend#15]
Complete:
Being able to search into a search bar for a workers name or skill and have all the matching entries pop up

Test:
1) search "Sebastian Jacob"
2) have my profile pop up
3) search carpenter 
4) have all the people with carpentry experience pop up

**Comment by thatdanghill** [comment]
Time: 5 hrs

TODO:
Research admin page search functionality
add in search bar
add in a column for each field in each model
