### ISSUE TITLE
As a worker I want to be able to choose multiple locations when signing up for the first time so I can be avaliable for more jobs 

### ISSUE THREAD

**Issue by seb-jacob** [labour-today/backend#18]
Complete:
Being able to choose multiple options when the sign up forum asks me to choose my area I work in 

Test:

Sign up as a worker and be able to choose more than one city as the area I work

**Comment by thatdanghill** [comment]
Time:
2 hrs

TODO:
Change models?
Edit forms

**Comment by ajhpark** [comment]
Database schema has to be changed to accomplish this, and that complicates the process since we have to change the data already in the database to fit the schema. Looking into it, but this additional complexity will increase time estimate
