### ISSUE TITLE
As a user I want to have secure banking, So I feel better about putting my credit card online.

### ISSUE THREAD

**Issue by johnreid01** [labour-today/backend#24]
Completion: Have a secured url when taking care of payment or personal information.

Test:
Adding the locked url to our webpage. 
Wouldn't know how to go about testing this.

**Comment by thatdanghill** [comment]
Equally safe alternative:
Put a blurb about how Stripe handles user data so payment can happen directly from the profile.
Not sure what users perceive as "secure" but the way it is implemented is already secure.
