### ISSUE TITLE
As a user I want to be able to input my hours daily. As a admin I want to be able to view the hours inputted by workers.

### ISSUE THREAD

**Issue by johnreid01** [labour-today/backend#43]
Completion: A user will be able to see the amount they are getting paid and the hours worked.

Test:
Create a profile.
Send the profile a job with details.
Accept said job.
Input hours.
See how much your making.

**Comment by seb-jacob** [comment]
Lets make this more of a priority @johnreid01 @thatdanghill @ajhpark

**Comment by johnreid01** [comment]
very important

**Comment by thatdanghill** [comment]
Need this to be a bit more defined/have wireframes. Is this just for the workers?

**Comment by ajhpark** [comment]
I am implementing this for workers.
The flow will be:
1. Worker goes to Profile, Jobs tab
2. Worker views details of the accepted job
3. There is a "Put in my daily hours" button
4. Worker fills out daily hours, which is displayed in both the admin page and the job detail page
