### ISSUE TITLE
As a contractor I want to see a notification when a worker has accepted my job without having to click 'view details' under 'your jobs' 

### ISSUE THREAD

**Issue by jordanlabourtoday** [labour-today/backend#45]
Completion:
When a contractor signs into his profile. If a worker has accepted the job he has posted, there should be a notification entailing the job has been filled.

Test:
create a  contractor profile 
post a job
sign out of the contractor profile
fill the job with a worker
sign into the contractor profile and see if there is a noticeable notification

**Comment by ajhpark** [comment]
wireframe mockup required
