### ISSUE TITLE
As a user, I want labourtoday.com to be ssl certified so I feel safe sending sensitive information to the site

### ISSUE THREAD

**Issue by ajhpark** [labour-today/backend#63]
get ssl certificate, make it work with heroku

**Comment by johnreid01** [comment]
@ajhpark Hows this coming along

**Comment by ajhpark** [comment]
it's a pain. Godaddy has really poor configuration compatibility with heroku. i spent last night trying to figure it out. still looking into it

**Comment by johnreid01** [comment]
@ajhpark Sounds good.
