### ISSUE TITLE
As a user I want to request a password Reset/Change, So if I forget my password I can reset it.

### ISSUE THREAD

**Issue by johnreid01** [labour-today/backend#79]
Completion: There will be a "Forgot Password?" button for users who forget their passwords.

Test: 
Create a user.
Select forgot password. 
Send an email confirmation with a password reset link. 
Reset Password.
Log back in using new password.

**Comment by ajhpark** [comment]
Password reset form is deployed. There is a bug where the server does not throw any errors but does not send the confirmation email.
Using the Django auth views and PasswordResetForm to implement:
https://github.com/django/django/blob/master/django/contrib/auth/views.py
(See def password_reset())
Been working on a solution for a while, would like to get a second opinion on a possible solution.
@thatdanghill
