### ISSUE TITLE
As a user I want to add a picture to my profile page, so that contractors and the LT team can see my face 

### ISSUE THREAD

**Issue by johnreid01** [labour-today/backend#8]

**Comment by johnreid01** [comment]
Completion: 
Workers can upload a picture from photo library or take one directly. 

Test: 
Create a Test profile 
Select add picture or take selfie 
Profile is created and added to the data base

**Comment by thatdanghill** [comment]
Time: 5 hr

TODO:
Research different picture upload functionalities
On profile page, add "upload" button
Change models: create one for photos?
Add picture to page. Have a default pic.
