### ISSUE TITLE
The contractor and worker flow (web) needs to be mobile optimized. Refer to the wireframes in zeplin.

### ISSUE THREAD

**Issue by johnreid01** [labour-today/backend#84]
Completion: The contractor will be able to navigate through the web easier.

Test: 
Login as a contractor on the web.
Request a worker.
Go through the worker flow have buttons bigger and easier to read.
Also have the web flow better.

**Comment by ajhpark** [comment]
From the meeting today this seems to be an important feature to implement correctly, with high priority.
@thatdanghill let's discuss how we will split this up, let me know which pages/templates still need optimizing
