### ISSUE TITLE
As a user I want to be able to edit my skills so I can access more jobs. 

### ISSUE THREAD

**Issue by johnreid01** [labour-today/backend#9]
Completion: 
Workers can sign into their account and add new skills or edit items they have to enhance their profiles. 

Test:
Create a Test profile 
Add current skills 
logout and login 
Edit skills or items and add new ones.
Review changes and save

**Comment by thatdanghill** [comment]
Time: 2 hr

TODO:
Add link in profile page to the register skills. 
Reroute "Save and Exit" to the profile page
